# The primary purpose of mailctl is providing IMAP/SMTP clients with the
# capabilities of renewal and authorization of OAuth2 credentials. 
# Accordingly only the OAuth2 related config entries are mandatory.

services_file: ~/.config/mailctl/services.yaml
oauth2_dir: ~/.local/var/mailctl
  # Saving OAuth2 credentials in files encrypted by GPG
# +
oauth2_dir: ~/.local/var/mailctl
encrypt_cmd:
  exec: gpg
  args:
    - --encrypt
    - --recipient
    - colin.torney@glasgow.ac.uk
    - -o
decrypt_cmd:
  exec: gpg
  args:
    - --decrypt
# -


